### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by x-gaming** [HyperactiveGuy/Bild-Hell-Rechner#1]
Die App stürzt ab wenn man auf die Schaltfläche "Save" klickt und anschließend das Dialogfenster wieder schließt (sowohl per rotem X als auch per "Abbrechen"). Die Ausnahme lautet "System.ArgumentException".

**Comment by HyperactiveGuy** [comment]
Seien Sie gefälligst still!

x-gaming ***@***.***> schrieb am Mo., 25. Juli 2022, 14:16:

**Comment by HyperactiveGuy** [comment]
Thank you, fixed it!
